# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2


include:
  # redox
  - board: nice_nano_v2
    shield: openwork_central_dongle dongle_display
    artifact-name: openwork_central_dongle
  - board: nice_nano_v2
    shield: openwork_central_left
    artifact-name: openwork_central_left
  - board: nice_nano_v2
    shield: openwork_peripheral_left
    artifact-name: openwork_peripheral_left
  - board: nice_nano_v2
    shield: openwork_peripheral_right
    artifact-name: openwork_peripheral_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: openwork_central_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: openwork_central_dongle_with_logging