file_format: "1"
id: openwork
name: openwork
type: shield
url: https://github.com/jimmerricks/swoop
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoders
  - underglow
siblings:
  - openwork_left
  - openwork_right
